apiVersion: v1
kind: Service
metadata:
  name: lms-service
  labels:
    app: lms
spec:
  selector:
    app: lms
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083
  type: ClusterIP
